In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
data = pd.read_csv('../02_NeuralCTR/train.csv')

In [4]:
data.head()

,label,integer_feature_1,integer_feature_2,integer_feature_3,integer_feature_4,integer_feature_5,integer_feature_6,integer_feature_7,integer_feature_8,integer_feature_9,...,categorical_feature_17,categorical_feature_18,categorical_feature_19,categorical_feature_20,categorical_feature_21,categorical_feature_22,categorical_feature_23,categorical_feature_24,categorical_feature_25,categorical_feature_26
0,0,49.0,520.0,0.0,353.0,5.0,0.0,0.0,0,2,...,1f7fc70b,628f1b8d,9512c20b,c5362157,a9ad4e8e,2b6a4b2f,bc71cd9d,9f4102b0,ff654802,2f33557c
1,0,NaN,408.0,NaN,NaN,NaN,0.0,0.0,-1,1,...,NaN,a1eb1511,0a1d513f,7fdb0729,747f6ecc,62682372,NaN,401a16fe,30436bfc,b757e957
2,0,28.0,37.0,2.0,5.0,4.0,5.0,1.0,974,14,...,753da5f3,d9f758ff,9512c20b,682d90ba,09afda28,307a0f03,f942364c,16e6b497,57e36578,a7ab145d
3,0,1.0,603.0,1.0,NaN,1.0,0.0,0.0,13,1,...,NaN,b8170bba,108a0699,47849e55,73b3f46d,d994ba60,NaN,328e967b,ff654802,2ba8d787
4,0,NaN,525.0,3.0,8.0,126.0,1.0,0.0,10,11,...,753da5f3,b8170bba,55191c09,0e29b5da,0683bc6f,47b99d80,d2b125b2,00a688ec,30436bfc,b757e957

In [17]:
print(data['label'].dtype)

int64

In [6]:
type(list(data.columns))

list

In [18]:
categorical_feat = [i for i in data.columns if data[i].dtype == 'str']
numerical_feat = [i for i in data.columns if data[i].dtype == float or data[i].dtype == int]
numerical_feat = numerical_feat[1:]

In [8]:
## preprocessing and handle the NAN values

## I put median value from NAN in integer_feature and max occurance for categorical_features

for i in numerical_feat:
    data[i] = data[i].fillna(data[i].median())


for i in categorical_feat:
    data[i] = data[i].fillna('missing')

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   label                   40000 non-null  int64
 1   integer_feature_1       40000 non-null  float64
 2   integer_feature_2       40000 non-null  float64
 3   integer_feature_3       40000 non-null  float64
 4   integer_feature_4       40000 non-null  float64
 5   integer_feature_5       40000 non-null  float64
 6   integer_feature_6       40000 non-null  float64
 7   integer_feature_7       40000 non-null  float64
 8   integer_feature_8       40000 non-null  int64
 9   integer_feature_9       40000 non-null  int64
 10  integer_feature_10      40000 non-null  float64
 11  integer_feature_11      40000 non-null  float64
 12  integer_feature_12      40000 non-null  float64
 13  integer_feature_13      40000 non-null  float64
 14  categorical_feature_1   40000 non-null  str
 15  categorical_feature_2   40000 non-null  str
 16  categorical_feature_3   40000 non-null  str
 17  categorical_feature_4   40000 non-null  str
 18  categorical_feature_5   40000 non-null  str
 19  categorical_feature_6   40000 non-null  str
 20  categorical_feature_7   40000 non-null  str
 21  categorical_feature_8   40000 non-null  str
 22  categorical_feature_9   40000 non-null  str
 23  categorical_feature_10  40000 non-null  str
 24  categorical_feature_11  40000 non-null  str
 25  categorical_feature_12  40000 non-null  str
 26  categorical_feature_13  40000 non-null  str
 27  categorical_feature_14  40000 non-null  str
 28  categorical_feature_15  40000 non-null  str
 29  categorical_feature_16  40000 non-null  str
 30  categorical_feature_17  40000 non-null  str
 31  categorical_feature_18  40000 non-null  str
 32  categorical_feature_19  40000 non-null  str
 33  categorical_feature_20  40000 non-null  str
 34  categorical_feature_21  40000 non-null  str
 35  categorical_feature_22  40000 non-null  str
 36  categorical_feature_23  40000 non-null  str
 37  categorical_feature_24  40000 non-null  str
 38  categorical_feature_25  40000 non-null  str
 39  categorical_feature_26  40000 non-null  str
dtypes: float64(11), int64(3), str(26)
memory usage: 20.1 MB

In [10]:
categorical_data_unique = {}

for i in categorical_feat:
    categorical_data_unique[i] = data[i].unique().shape

In [11]:
categorical_data_unique

{'categorical_feature_1': (13191,),
 'categorical_feature_2': (3757,),
 'categorical_feature_3': (4968,),
 'categorical_feature_4': (1851,),
 'categorical_feature_5': (4253,),
 'categorical_feature_6': (3,),
 'categorical_feature_7': (3111,),
 'categorical_feature_8': (741,),
 'categorical_feature_9': (22,),
 'categorical_feature_10': (11585,),
 'categorical_feature_11': (5569,),
 'categorical_feature_12': (7723,),
 'categorical_feature_13': (9,),
 'categorical_feature_14': (904,),
 'categorical_feature_15': (2025,),
 'categorical_feature_16': (43,),
 'categorical_feature_17': (4,),
 'categorical_feature_18': (341,),
 'categorical_feature_19': (14,),
 'categorical_feature_20': (13509,),
 'categorical_feature_21': (9003,),
 'categorical_feature_22': (12629,),
 'categorical_feature_23': (5095,),
 'categorical_feature_24': (3504,),
 'categorical_feature_25': (36,),
 'categorical_feature_26': (24,)}

In [12]:
## Train test split

X = data.drop(columns=['label'])
y = data['label']

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state = 42
)

In [14]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler

scaler = StandardScaler()

In [20]:
# scaling numerical data

X_train_num = scaler.fit_transform(X_train[numerical_feat])
X_test_num = scaler.transform(X_test[numerical_feat])

X_test_num.shape

(8000, 13)

In [21]:
## prepare categorical data

X_train_cat = X_train[categorical_feat].astype('str')
X_test_cat = X_test[categorical_feat].astype('str')

In [22]:
X_train_cat.head()

,categorical_feature_1,categorical_feature_2,categorical_feature_3,categorical_feature_4,categorical_feature_5,categorical_feature_6,categorical_feature_7,categorical_feature_8,categorical_feature_9,categorical_feature_10,...,categorical_feature_17,categorical_feature_18,categorical_feature_19,categorical_feature_20,categorical_feature_21,categorical_feature_22,categorical_feature_23,categorical_feature_24,categorical_feature_25,categorical_feature_26
14307,5dc16de2,d372df4b,62a5fee5,14841cc2,664ff944,6fcd6dcb,7dfd04ed,038e402d,2e4e821f,baac6e18,...,missing,b8170bba,9512c20b,39fffff8,a3e62678,1a7d6a4a,missing,2f01f6d1,991321ea,b757e957
17812,missing,2027c0d0,64fa3e43,a8e2f1c9,1315f676,6fcd6dcb,2d72123e,20aa0da1,25dd8f9a,missing,...,missing,7232d217,9512c20b,missing,missing,missing,missing,59c61d47,321935cd,6c730e3e
11020,7db3a66e,ea9a22db,48c07a22,6faef306,e755064d,6fcd6dcb,fad5de89,1c904173,2e4e821f,f72b2fb9,...,1f7fc70b,d9f758ff,9512c20b,8e0391a0,2798c0f9,3e29a205,e54bad85,348246ae,30436bfc,2f33557c
15158,e7b94768,1d52b21b,73369e23,386c49ee,4ff7b61d,6fcd6dcb,3d65ae52,8f551379,2e4e821f,79d81167,...,1f7fc70b,b8170bba,139221a3,df359cec,b5ed6108,e68b6fba,b8df7c07,3581f19f,ff654802,2ccea557
24990,436a9128,11074985,200258ea,f7f54f97,664ff944,6fcd6dcb,11525a1a,09f8a09d,2e4e821f,23d4c410,...,753da5f3,b8170bba,139221a3,1b15b20d,c89adb62,bffbac21,4fb3556e,941f47a2,ff654802,2f33557c

In [59]:
## creating DLRM for numerical features

from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense,Input,Embedding,StringLookup,Dot,Concatenate
import tensorflow as tf

In [78]:
numerical_input = Input(shape=(X_train_num.shape[1],),name="numerical_input")

In [79]:
# implement layers of dense
embedding_dim = 16 ## we will convert str features in 16 dimensions features


dense_model = Sequential([
    Dense(64, activation="relu"),
    Dense(32, activation="relu"),
    Dense(embedding_dim, activation="relu")
])

dense = dense_model(numerical_input)

In [80]:
## embedding of features for categorical data

categorical_inputs = []
categorical_embeddings = []

In [81]:

for feature in categorical_feat:
    print("Processing:", feature)

    input_layer = Input(
        shape=(1,),
        dtype=tf.string,
        name=feature
    )

    lookup = StringLookup(
        num_oov_indices=1,
        output_mode="int"
    )

    lookup.adapt(X_train_cat[feature].astype(str).tolist())

    encoded = lookup(input_layer)

    embedding = Embedding(
        input_dim=lookup.vocabulary_size(),
        output_dim=16
    )(encoded)

    embedding = tf.keras.layers.Flatten()(embedding)

    categorical_inputs.append(input_layer)
    categorical_embeddings.append(embedding)

print("DONE")

Processing: categorical_feature_1
Processing: categorical_feature_2
Processing: categorical_feature_3
Processing: categorical_feature_4
Processing: categorical_feature_5
Processing: categorical_feature_6
Processing: categorical_feature_7
Processing: categorical_feature_8
Processing: categorical_feature_9
Processing: categorical_feature_10
Processing: categorical_feature_11
Processing: categorical_feature_12
Processing: categorical_feature_13
Processing: categorical_feature_14
Processing: categorical_feature_15
Processing: categorical_feature_16
Processing: categorical_feature_17
Processing: categorical_feature_18
Processing: categorical_feature_19
Processing: categorical_feature_20
Processing: categorical_feature_21
Processing: categorical_feature_22
Processing: categorical_feature_23
Processing: categorical_feature_24
Processing: categorical_feature_25
Processing: categorical_feature_26
DONE

In [82]:
## Concate the numerical feature and categorical feature

feature_vectors = [
    dense
] + categorical_embeddings

In [83]:
len(feature_vectors)

27

In [84]:
instructions = []

for i in range(len(feature_vectors)):
    for j in range(i+1,len(feature_vectors)):
        instruction = Dot(axes=1)([feature_vectors[i],feature_vectors[j]])
        instructions.append(instruction)

In [85]:
instructions_op = Concatenate()([dense]+instructions)

In [86]:
instructions_op.shape

(None, 367)

In [87]:


x = Dense(64, activation='relu')(instructions_op)
x = Dense(32, activation='relu')(x)
output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=[numerical_input] + categorical_inputs, outputs=output)

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [89]:
# model.summary()

In [90]:
train_inputs = {
    "numerical_input": tf.convert_to_tensor(
        X_train_num,
        dtype=tf.float32
    )
}

for feature in categorical_feat:
    train_inputs[feature] = tf.convert_to_tensor(
        X_train_cat[feature].values,
        dtype=tf.string
    )

test_inputs = {
    "numerical_input": tf.convert_to_tensor(
        X_test_num,
        dtype=tf.float32
    )
}

for feature in categorical_feat:
    test_inputs[feature] = tf.convert_to_tensor(
        X_test_cat[feature].values,
        dtype=tf.string
    )

In [91]:
print(y_train.dtype)
print(train_inputs["numerical_input"].dtype)
print(train_inputs["categorical_feature_1"].dtype)

int64
<dtype: 'float32'>
<dtype: 'string'>

In [92]:
history = model.fit(
    train_inputs,
    y_train,
    epochs=50,
    batch_size=32,
    validation_data=(
        test_inputs,
        y_test
    )
)

Epoch 1/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 28s 17ms/step - accuracy: 0.9677 - loss: 0.1501 - val_accuracy: 0.9694 - val_loss: 0.1305
Epoch 2/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.9681 - loss: 0.1031 - val_accuracy: 0.9674 - val_loss: 0.1618
Epoch 3/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9858 - loss: 0.0422 - val_accuracy: 0.9559 - val_loss: 0.2212
Epoch 4/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9943 - loss: 0.0168 - val_accuracy: 0.9439 - val_loss: 0.2885
Epoch 5/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9973 - loss: 0.0089 - val_accuracy: 0.9501 - val_loss: 0.3515
Epoch 6/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9988 - loss: 0.0046 - val_accuracy: 0.9556 - val_loss: 0.4014
Epoch 7/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9991 - loss: 0.0028 - val_accuracy: 0.9499 - val_loss: 0.4419
Epoch 8/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9993 - loss: 0.0024 - val_accuracy: 0.9496 - val_loss: 0.4484
Epoch 9/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9999 - loss: 5.7019e-04 - val_accuracy: 0.9513 - val_loss: 0.5508
Epoch 10/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.9996 - loss: 0.0014 - val_accuracy: 0.9567 - val_loss: 0.5055
Epoch 11/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.9996 - loss: 0.0013 - val_accuracy: 0.9355 - val_loss: 0.6118
Epoch 12/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9997 - loss: 0.0010 - val_accuracy: 0.9415 - val_loss: 0.6256
Epoch 13/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9996 - loss: 0.0012 - val_accuracy: 0.9524 - val_loss: 0.5340
Epoch 14/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9998 - loss: 7.4157e-04 - val_accuracy: 0.9433 - val_loss: 0.5324
Epoch 15/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.9998 - loss: 7.4792e-04 - val_accuracy: 0.9567 - val_loss: 0.5913
Epoch 16/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9999 - loss: 3.4354e-04 - val_accuracy: 0.9532 - val_loss: 0.6080
Epoch 17/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9999 - loss: 1.7104e-04 - val_accuracy: 0.9486 - val_loss: 0.6458
Epoch 18/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9999 - loss: 2.4079e-04 - val_accuracy: 0.9374 - val_loss: 0.6616
Epoch 19/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 0.9999 - loss: 2.6761e-04 - val_accuracy: 0.9469 - val_loss: 0.7032
Epoch 20/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 4.6011e-06 - val_accuracy: 0.9517 - val_loss: 0.7443
Epoch 21/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 1.3836e-06 - val_accuracy: 0.9523 - val_loss: 0.7664
Epoch 22/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 8.7075e-07 - val_accuracy: 0.9524 - val_loss: 0.7894
Epoch 23/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 5.3847e-07 - val_accuracy: 0.9525 - val_loss: 0.8133
Epoch 24/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 3.2150e-07 - val_accuracy: 0.9525 - val_loss: 0.8386
Epoch 25/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 1.8001e-07 - val_accuracy: 0.9528 - val_loss: 0.8661
Epoch 26/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 9.4266e-08 - val_accuracy: 0.9526 - val_loss: 0.8952
Epoch 27/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 4.7907e-08 - val_accuracy: 0.9528 - val_loss: 0.9228
Epoch 28/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 2.5508e-08 - val_accuracy: 0.9525 - val_loss: 0.9496
Epoch 29/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 1.4327e-08 - val_accuracy: 0.9524 - val_loss: 0.9734
Epoch 30/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 8.4374e-09 - val_accuracy: 0.9524 - val_loss: 0.9972
Epoch 31/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 5.1293e-09 - val_accuracy: 0.9523 - val_loss: 1.0179
Epoch 32/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 3.2614e-09 - val_accuracy: 0.9521 - val_loss: 1.0381
Epoch 33/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 2.1002e-09 - val_accuracy: 0.9524 - val_loss: 1.0566
Epoch 34/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 1.3957e-09 - val_accuracy: 0.9524 - val_loss: 1.0744
Epoch 35/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 9.5436e-10 - val_accuracy: 0.9524 - val_loss: 1.0910
Epoch 36/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 6.6487e-10 - val_accuracy: 0.9525 - val_loss: 1.1070
Epoch 37/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 4.7801e-10 - val_accuracy: 0.9525 - val_loss: 1.1212
Epoch 38/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 3.5124e-10 - val_accuracy: 0.9525 - val_loss: 1.1350
Epoch 39/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 2.6533e-10 - val_accuracy: 0.9525 - val_loss: 1.1468
Epoch 40/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 2.0990e-10 - val_accuracy: 0.9528 - val_loss: 1.1575
Epoch 41/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 16s 16ms/step - accuracy: 1.0000 - loss: 1.6680e-10 - val_accuracy: 0.9529 - val_loss: 1.1670
Epoch 42/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 1.3879e-10 - val_accuracy: 0.9530 - val_loss: 1.1755
Epoch 43/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 14ms/step - accuracy: 1.0000 - loss: 1.1650e-10 - val_accuracy: 0.9531 - val_loss: 1.1828
Epoch 44/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 1.0093e-10 - val_accuracy: 0.9531 - val_loss: 1.1889
Epoch 45/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 8.9386e-11 - val_accuracy: 0.9531 - val_loss: 1.1944
Epoch 46/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 8.2364e-11 - val_accuracy: 0.9532 - val_loss: 1.1991
Epoch 47/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 7.6590e-11 - val_accuracy: 0.9532 - val_loss: 1.2034
Epoch 48/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 7.1061e-11 - val_accuracy: 0.9532 - val_loss: 1.2072
Epoch 49/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 1.0000 - loss: 6.6943e-11 - val_accuracy: 0.9532 - val_loss: 1.2104
Epoch 50/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 6.3184e-11 - val_accuracy: 0.9532 - val_loss: 1.2136

ROC-AUC  : 0.7129982781385366
Accuracy : 0.9665
PR-AUC   : 0.08367227650050578
Log Loss : 0.1373307704925537
F1 Score : 0.0
Precision: 0.0
Recall   : 0.0

Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      9665
           1       0.00      0.00      0.00       335

    accuracy                           0.97     10000
   macro avg       0.48      0.50      0.49     10000
weighted avg       0.93      0.97      0.95     10000


Confusion Matrix:
[[9665    0]
 [ 335    0]]

c:\Users\krish\anaconda3\envs\pytorch_env\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\krish\anaconda3\envs\pytorch_env\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\krish\anaconda3\envs\pytorch_env\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\krish\anaconda3\envs\pytorch_env\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [93]:
data_test = pd.read_csv('../02_NeuralCTR/test.csv')

In [94]:
# Numerical features
for feature in numerical_feat:
    data_test[feature] = data_test[feature].fillna(
        data[feature].median()
    )

# Categorical features
for feature in categorical_feat:
    data_test[feature] = data_test[feature].fillna("missing")

# Separate features
X_test_new = data_test.drop(columns=["label"])
y_test_new = data_test["label"]

# Scale numerical features using the ALREADY fitted scaler
X_test_new_num = scaler.transform(
    X_test_new[numerical_feat]
)

# Keep categorical features as strings
X_test_new_cat = X_test_new[categorical_feat].astype(str)

In [96]:
test_inputs = [X_test_new_num]

for feature in categorical_feat:
    test_inputs.append(
        tf.convert_to_tensor(
            X_test_new_cat[feature].to_numpy().reshape(-1, 1),
            dtype=tf.string
        )
    )

In [97]:
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    average_precision_score,
    log_loss,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

# True labels
y_true = np.asarray(y_test_new).astype(int).ravel()

# Model predictions
y_pred = model.predict(test_inputs).ravel()

# Default threshold
threshold = 0.5
y_pred_class = (y_pred >= threshold).astype(int)

# Metrics
roc_auc = roc_auc_score(y_true, y_pred)
accuracy = accuracy_score(y_true, y_pred_class)
pr_auc = average_precision_score(y_true, y_pred)
logloss = log_loss(y_true, y_pred)
f1 = f1_score(y_true, y_pred_class)
precision = precision_score(y_true, y_pred_class)
recall = recall_score(y_true, y_pred_class)

print("ROC-AUC  :", roc_auc)
print("Accuracy :", accuracy)
print("PR-AUC   :", pr_auc)
print("Log Loss :", logloss)
print("F1 Score :", f1)
print("Precision:", precision)
print("Recall   :", recall)

print("\nClassification Report:")
print(classification_report(y_true, y_pred_class))

print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred_class))

313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step
ROC-AUC  : 0.6028936538209111
Accuracy : 0.9469
PR-AUC   : 0.04926526216061079
Log Loss : 0.6328853964805603
F1 Score : 0.05008944543828265
Precision: 0.0625
Recall   : 0.041791044776119404

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      9665
           1       0.06      0.04      0.05       335

    accuracy                           0.95     10000
   macro avg       0.51      0.51      0.51     10000
weighted avg       0.94      0.95      0.94     10000


Confusion Matrix:
[[9455  210]
 [ 321   14]]